#!/bin/sh

__use_internal() {
    local __use_alt_group __use_alt_name __use_alt_config __use_alt_value
    # Remove from PATH
    while read __use_alt_group __use_alt_name __use_alt_config __use_alt_value; do
        if [ "$__use_alt_group" = "$1" ]; then
            if [ "$__use_alt_config" = "path" ]; then
                PATH=`echo ":$PATH:" | sed 's#//#/#g' | sed -e 's#:'"$__use_alt_value"':#:#g' -e 's#^:*##' -e 's#:*$##'`
            fi
        fi
    done <~/.use.rc

    # Set PATH and other envs
    while read __use_alt_group __use_alt_name __use_alt_config __use_alt_value; do
        if [ "$__use_alt_group" = "$1" ]; then
            if [ "$__use_alt_name" = "$2" ]; then
                if [ "$__use_alt_config" = "path" ]; then
                    PATH="$__use_alt_value:$PATH"
                fi
                if [ "$__use_alt_config" = "env" ]; then
                    eval export "$__use_alt_value"
                    echo export "$__use_alt_value"
                fi
                if [ "$__use_alt_config" = "command" ]; then
                    eval "$__use_alt_value" || true
                fi
            fi
        fi
    done <~/.use.rc
}

use() {
    local __use_alt_group __use_alt_name __use_alt_config __use_alt_value __use_found

    if [ "$1" = "help" -o "$1" = "--help" -o "$1" = "-h" -o -z "$1" ]; then
        echo "Usage: use alternative version"
    elif ! [ -f "$HOME/.use.rc" ]; then
        echo "Configuration file ~/.use.rc missing."
    elif [ -z "$2" ]; then
        __use_alternatives=`sed -n "/^$1"'[ \t]/s#^[^ \t]*[ \t]*\([^ \t]*\).*#\1#p' <~/.use.rc | sort | uniq | paste '-sd '`
        echo "Alternatives for $1: $__use_alternatives"
    else
        __use_found=false
        while read __use_alt_group __use_alt_name __use_alt_config __use_alt_value; do
            if [ "$__use_alt_group" = "$1" ]; then
                if [ "$__use_alt_name" = "$2" ]; then
                    __use_found=true
                fi
            fi
        done <~/.use.rc

        if ! $__use_found; then
            echo "Alternative $1 ($2) not found"
        else
            __use_internal "$1" "$2"
        fi
    fi
}
