#!/bin/sh

INPUT="$1"
OUTPUT="$2"

msg_exec() {
    echo "$@" >&2
    "$@"
}

if ! [ -e "$INPUT" ]; then
    echo "File input not found ($INPUT)." >&2
    exit 1
fi

if [ -z "$OUTPUT" ]; then
   OUTPUT=`dirname "$INPUT"`/`basename "$INPUT" .pdf`.embed.pdf
fi

msg_exec gs \
    -dNOPAUSE -dBATCH -sDEVICE=pdfwrite \
    -dPDFSETTINGS=/prepress -dEmbedAllFonts=true \
    -dNOPLATFONTS \
    "-sOutputFile=$OUTPUT" \
    -f "$INPUT"
