#!/bin/sh

__MACHINE="$1"
shift

env \
    ANSIBLE_HOST_KEY_CHECKING=false \
    ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' \
    ansible-playbook \
        --private-key=.vagrant/machines/$__MACHINE/virtualbox/private_key \
        --connection=ssh \
        --timeout=30 \
        -u vagrant \
        -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory \
        --become \
        --limit="$__MACHINE" \
        "$@"
